name: RebelsTransfer
version: "1.2.3"
main: wailord2.rebelstransfer.rebelstransfer.RebelsTransfer
api-version: "1.13"
authors: [wailord2]
description: Plugin to trade claimblocks between players
commands:
  cbpay:
    description: Used to send claimblocks to other players
    usage: "ยง6Correct usage: /cbpay [name] [amount]"


