name: AutoTPO
version: "1.3"
main: wailord2.autotpo.autotpo.AutoTPO
api-version: "1.13"
authors: [wailord2]
description: Plugin used to automatically execute tpo check.
commands:
  tpostart:
    description: Start automated tpo check.
  tpopause:
    description: Pause automated tpo check.
  tpostop:
    description: Stop automated tpo check.
