name: AutoTPO
version: "1.5"
main: wailord2.autotpo.autotpo.AutoTPO
api-version: "1.13"
authors: [wailord2]
description: Plugin used to automatically execute tpo check.
commands:
  tpostart:
    description: Start automated tpo check.
    usage: /tpostart [interval] or /tpostart [interval] [counttostartat]
  tpostop:
    description: Stop automated tpo check.
