name: SimpleNick
version: "1.11"
main: wailord2.rebelsnick.rebelsnick.RebelsNick
api-version: "1.13"
authors: [wailord2]
description: Plugin to change nicknames and colors of names.
commands:
  nick:
    description: Changes the nickname of the player
  nickcolor:
    description: Change the color of the players nickname
permissions:
  simplenick.changeothernick:
    default: op
  simplenick.changenick:
    default: op
  simplenick.black:
    default: op
  simplenick.dark_blue:
    default: op
  simplenick.dark_green:
    default: op
  simplenick.dark_aqua:
    default: op
  simplenick.dark_red:
    default: op
  simplenick.dark_purple:
    default: op
  simplenick.gold:
    default: op
  simplenick.gray:
    default: op
  simplenick.dark_gray:
    default: op
  simplenick.blue:
    default: op
  simplenick.green:
    default: op
  simplenick.aqua:
    default: op
  simplenick.red:
    default: op
  simplenick.light_purple:
    default: op
  simplenick.yellow:
    default: op
  simplenick.white:
    default: op